# Copyright rigélblu inc.
# All rights reserved.

version: '3'
services:
  mgn-concept:
    build:
      args:
        NEXT_PUBLIC_ANALYTICS_ID: ${NEXT_PUBLIC_ANALYTICS_ID}
        NEXT_PUBLIC_STRIPE_PAYMENT_URL: ${NEXT_PUBLIC_STRIPE_PAYMENT_URL}
        NODE_ENV: ${NODE_ENV}
      context: .
      target: runner-ssg
    env_file: .env.development
    image: mgn-concept
    ports:
      - '8080:8080'
