# Copyright rigélblu inc. All rights reserved.

version: '3'
services:
  mgn-site:
    build:
      args:
        NEXT_PUBLIC_ANALYTICS_ID: ${NEXT_PUBLIC_ANALYTICS_ID}
        NEXT_PUBLIC_STRIPE_PAYMENT_URL: ${NEXT_PUBLIC_STRIPE_PAYMENT_URL}
        NODE_ENV: ${NODE_ENV}
      context: .
      target: runner-ssg
    env_file:
      - .env.local
    image: mgn-site
    ports:
      - '8080:8080'
