# Copyright rigélblu inc.
# All rights reserved.

description: mgn / concept / gcr / tag
filename: ci/cloudbuild.yaml
github:
  name: magin-concept
  owner: rigelblu
  push:
    tag: build-branch
name: mgn-site-gcr-tag
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: branch-tagged
  _ENV_ANALYTICS_ID: G-VSBDW9PNSD
  _ENV_NODE_ENV: production
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _REGION: us-central1
  _SERVICE_NAME: mgn-public-site
  _TRAFFIC_TO_LATEST: 'false'
tags:
  - magin-public-site
  - branch-tagged
