description: mgn / concept / gcr / pull-request
filename: ci/cloudbuild.yaml
name: mgn-site-gcr-pr---dev
repositoryEventConfig:
  pullRequest:
    branch: .*
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
  repository: ''
  repositoryType: GITHUB
resourceName: ''
serviceAccount: ''
substitutions:
  _ANALYTICS_ID: ''
  _DEPLOY_TAG: live
  _GCP_ARTIFACT: ''
  _GCP_MAX_INSTANCES: '1'
  _GCP_MIN_INSTANCES: '0'
  _GCP_REGION: ''
  _GCP_SERVICE_NAME: mgn-site
  _NODE_ENV: development
  _STRIPE_PAYMENT_URL: ''
  _TRAFFIC_TO_LATEST: 'false'
  _TRIGGER_REASON: pull-request
