# Copyright rigélblu inc.
# All rights reserved.

description: <domin> / <app> / gcr / tag
filename: ci/cloudbuild.yaml
github:
  name: <add>
  owner: rigelblu
  push:
    tag: build-branch
name: gcr-tag
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: branch-tagged
  _ENV_ANALYTICS_ID: ''
  _ENV_NODE_ENV: ''
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _REGION: us-central1
  _SERVICE_NAME: <add>
  _TRAFFIC_TO_LATEST: 'false'
