description: mgn / concept / gcr / pull-request
filename: ci/cloudbuild.yaml
name: mgn-site-gcr-pr---dev
repositoryEventConfig:
  pullRequest:
    branch: .*
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
  repository: ''
  repositoryType: GITHUB
resourceName: ''
serviceAccount: ''
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: live
  _ENV_ANALYTICS_ID: G-867B5HDFZ4
  _ENV_NODE_ENV: development
  _ENV_STRIPE_PAYMENT_URL: ''
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _REGION: us-central1
  _SERVICE_NAME: mgn-public-site
  _TRAFFIC_TO_LATEST: 'false'
  _TRIGGER_REASON: pull-request
