description: magin / concept / gcr / pull request
filename: ci/cloudbuild.gcr.yaml
github:
  name: magin-concept
  owner: rigelblu
  pullRequest:
    branch: .*
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: mgn-concept--gcr--pr
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAGS: staging,preview
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _NODE_ENV: development
  _REGION: us-central1
  _SERVICE_NAME: mgn-concept
  _TRAFFIC_TO_LATEST: 'false'
