# Copyright rigélblu inc.
# All rights reserved.

description: mgn / concept / gcr / manual branch
gitFileSource:
  path: ci/cloudbuild.yaml
  repoType: GITHUB
  revision: refs/heads/main
  uri: https://github.com/rigelblu/magin-concept
name: mgn-site-gcr-manual
sourceToBuild:
  ref: refs/heads/main
  repoType: GITHUB
  uri: https://github.com/rigelblu/magin-concept
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: branch-manual
  _ENV_ANALYTICS_ID: G-867B5HDFZ4
  _ENV_NODE_ENV: development
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _REGION: us-central1
  _SERVICE_NAME: <add>
  _TRAFFIC_TO_LATEST: 'false'
  _TRIGGER_REASON: branch-manual
