description: magin / concept / gcr / continuous delivery + release
filename: ci/cloudbuild.gcr.yaml
github:
  name: magin-concept
  owner: rigelblu
  push:
    branch: ^main$
name: mgn-concept--gcr--cdp
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAGS: staging
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _NODE_ENV: development
  _REGION: us-central1
  _SERVICE_NAME: mgn-concept
  _TRAFFIC_TO_LATEST: 'false'
