description: mgn / concept / gcr / manual branch
gitFileSource:
  path: ci/cloudbuild.yaml
  repository: ''
  revision: refs/heads/main
name: mgn-site-gcr-manual---prod
serviceAccount: ''
sourceToBuild:
  ref: refs/heads/main
  repository: ''
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: staging
  _ENV_ANALYTICS_ID: G-TKT2WEH9ES
  _ENV_NODE_ENV: production
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _REGION: us-central1
  _SERVICE_NAME: mgn-public-site
  _TRAFFIC_TO_LATEST: 'false'
  _TRIGGER_REASON: branch-manual
