description: mgn / concept / gcr / continuous delivery
filename: ci/cloudbuild.yaml
name: mgn-site-gcr-cd---prod
repositoryEventConfig:
  push:
    branch: ^main$
  repository: ''
  repositoryType: GITHUB
serviceAccount: ''
substitutions:
  _ANALYTICS_ID: ''
  _DEPLOY_TAG: staging
  _GCP_ARTIFACT: ''
  _GCP_MAX_INSTANCES: '1'
  _GCP_MIN_INSTANCES: '0'
  _GCP_REGION: ''
  _GCP_SERVICE_NAME: mgn-site
  _NODE_ENV: production
  _STRIPE_PAYMENT_URL: ''
  _TRAFFIC_TO_LATEST: 'false'
  _TRIGGER_REASON: continuous-delivery
