# Copyright rigélblu inc.
# All rights reserved.

description: mgn / magin concept / gcr / manual on branch
filename: ci/cloudbuild.yaml
github:
  name: magin-concept
  owner: rigelblu
  pullRequest:
    branch: .*
    commentControl: COMMENTS_ENABLED
name: trigger-gcr-branch
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: manual-branch
  _ENV_ANALYTICS_ID: ''
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _NODE_ENV: development
  _REGION: us-central1
  _SERVICE_NAME: mgn-concept
  _TRAFFIC_TO_LATEST: 'false'
