# Copyright rigélblu inc.
# All rights reserved.

description: mgn / concept / gcr / continuous delivery + release
filename: ci/cloudbuild.yaml
github:
  name: <add>
  owner: rigelblu
  push:
    branch: ^main$
name: gcr-cdp
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: staging
  _ENV_ANALYTICS_ID: ''
  _ENV_NODE_ENV: ''
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _REGION: us-central1
  _SERVICE_NAME: <add>
  _TRAFFIC_TO_LATEST: 'true'
