approvalConfig:
  approvalRequired: true
description: mgn / concept / gcr / pull-request
filename: ci/cloudbuild.yaml
github:
  name: magin-concept
  owner: rigelblu
  pullRequest:
    branch: .*
    commentControl: COMMENTS_ENABLED
name: mgn-site-gcr-pr
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: staging
  _ENV_ANALYTICS_ID: ''
  _ENV_NODE_ENV: ''
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _REGION: us-central1
  _SERVICE_NAME: mgn-public-site
  _TRAFFIC_TO_LATEST: 'false'
