description: mgn / concept / gcr / continuous delivery
filename: ci/cloudbuild.yaml
name: mgn-site-gcr-cd---prod
repositoryEventConfig:
  push:
    branch: ^main$
  repository: ''
  repositoryType: GITHUB
serviceAccount: ''
substitutions:
  _ARTIFACT: us-central1-docker.pkg.dev
  _DEPLOY_TAG: staging
  _ENV_ANALYTICS_ID: G-TKT2WEH9ES
  _ENV_NODE_ENV: production
  _ENV_STRIPE_PAYMENT_URL: ''
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _REGION: us-central1
  _SERVICE_NAME: mgn-public-site
  _TRAFFIC_TO_LATEST: 'false'
  _TRIGGER_REASON: continuous-delivery
