description: mgn / concept / gcr / manual branch
gitFileSource:
  path: ci/cloudbuild.yaml
  repository: ''
  revision: refs/heads/main
name: mgn-site-gcr-manual---prod
serviceAccount: ''
sourceToBuild:
  ref: refs/heads/main
  repository: ''
substitutions:
  _ANALYTICS_ID: ''
  _DEPLOY_TAG: staging
  _GCP_ARTIFACT: ''
  _GCP_MAX_INSTANCES: '1'
  _GCP_MIN_INSTANCES: '0'
  _GCP_REGION: ''
  _GCP_SERVICE_NAME: mgn-site
  _NODE_ENV: production
  _STRIPE_PAYMENT_URL: ''
  _TRAFFIC_TO_LATEST: 'false'
  _TRIGGER_REASON: branch-manual
