#!/bin/sh
# Copyright rigélblu inc.
# All rights reserved.

. "$(dirname "$0")/_/husky.sh"

set -e

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCH="main"

if [ "$BRANCH" = "$PROTECTED_BRANCH" ]; then
  pnpm lint
  pnpm test
  pnpm build:ssg
fi
