#!/bin/sh
# Copyright rigélblu inc. All rights reserved.

. "$(dirname "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCH="main"

if [ "$BRANCH" = "$PROTECTED_BRANCH" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

# TODO: in the future, only run these CI/CD system
FILES=( ".dockerignore" ".eslint*" ".linkstagerc.js" ".stylelintrc.js" "additional.d.ts" )
FILES+=( "docker-compose.yml" "Dockerfile" "next-env.d.ts" "next.config.js" "package.json" )
FILES+=( "pnpm-lock.yaml" "postcss.config.js" "server.ts" "tailwind.config.js" "tsconfig.json" )

if ! git diff --cached --quiet -- "${FILES[@]}"; then
  echo "Build files changes that could affect creating the build"
  echo "CONSIDER running:"
  echo "   pnpm build"
  echo "   pnpm lint"
  echo "   docker compose up --build"
fi

pnpm lint-staged
