#!/usr/bin/env sh
# Copyright rigélblu inc.
# All rights reserved.

. "$(dirname -- "$0")/_/husky.sh"

# Require pull request
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "main" ]; then
  echo "You can't merge directly to main branch. Submit a pull request"
  exit 1
fi

# Trigger builds
FILES=( ".dockerignore" ".eslint*" ".linkstagerc.js" ".stylelintrc.js" "additional.d.ts" )
FILES+=( "docker-compose.yml" "Dockerfile" "next-env.d.ts" "next.config.js" "package.json" )
FILES+=( "postcss.config.js" "server.js" "tailwind.config.js" "tsconfig*" "tsconfigs/*" "yarn.lock" )

if [ git diff --cached --quiet -- $FILES ]; then
  yarn build:prod
fi

if [ git diff --cached --quiet -- Dockerfile ]; then
  docker-compose build; docker-compose up -d
fi

# TODO: enable once we add unit tests
yarn test
