#!/bin/sh
# Copyright rigélblu inc.
# All rights reserved.

. "$(dirname "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCH="main"

if [ "$BRANCH" = "$PROTECTED_BRANCH" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

pnpm lint-staged
