#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Require pull request
if [ "$branch" = "main" ]; then
  echo "You can't merge directly to main branch. Submit a pull request"
  exit 1
fi

# Trigger builds
FILES=( ".eslint*" ".linkstagerc.js" )
FILES+=( "additional.js" "next.config.js" "next-env.d.ts" "package.json" "tailwind.config.js" "tsconfig/*" "tsconfig*" "yarn.lock")
if [ git diff --cached --quiet -- $FILES ]; then
  yarn build:ssg
fi

if [ git diff --cached --quiet -- Dockerfile ]; then
  yarn docker:rebuild
fi

yarn test
